FarmServers: "{{ hostvars[groups['all'][0]]['ansible_fqdn'] }}"
StoreVirtualPath: /Citrix/Store
TransportType: HTTPS
GatewaySTAUrls: https://{{ hostvars[groups['all'][0]]['ansible_fqdn'] }}
GatewayName: NSG1
#Storefront URL
HostbaseUrl: https://INTERNAL-FQDN #https://storefront.contoso.local
#Netscaler Gateway URL
GatewayUrl: https://EXTERNAL-FQDN #https://citrix.contoso.com
SSLCert: wild_contoso_com_exp3_14_2024.pfx #wildcard_contoso_com.pfx
CertPass: SUPERSECRET #supersecretpass!