---
- name: Install VDA Components
  win_package:
    path: "{{ citrix_path }}\\x64\\XenDesktop Setup\\XenDesktopVdaSetup.exe"
    arguments: /quiet /optimize /components vda /controllers '{{ hostvars[groups['all'][0]]['ansible_hostname'] }}' /enable_remote_assistance /enable_hdx_ports /enable_real_time_transport /virtualmachine /noreboot /noresume /logpath 'C:\Logs' /masterimage
    state: present
    product_id: StorefrontInstall
    expected_return_code: [0, 3, 3010]
  register: vda_install

- name: Reboot after VDA
  win_reboot:

- name: Resume VDA Install
  win_package:
    path: C:\ProgramData\Citrix\XenDesktopSetup\XenDesktopVdaSetup.exe
    state: present
    expected_return_code: [0, 3, 3010]
    creates_service: BrokerAgent
  when: vda_install.changed
  register: vda_install2

- name: Reboot after vda install
  win_reboot:
