---
- hosts: all
  roles:
  # - windowsupdates
   - prereqs
   - ddc
   - director
   - createsite
   - site-hydrate #edit defaults\main.yml, 
   - storefront
   - storefront-init #edit defaults\main.yml, files\cert.pfx, 
   - SSLCert
   - vda